### ISSUE TITLE
Rename or redefine the db.sqlite location

### ISSUE THREAD

**Issue by ewallz** [luizbills/create-wordpress-sqlite#5]
Hi, by default the sqlite db will be downloaded at wp-content/database/db.sqlite.
Is it possible to:
1. Rename the db.sqlite to something else like db_yreuyreury.sqlite?
2. Relocate/move the sqlite db to a different folder location and define the location somewhere?

I'm just trying out this wpsqlite solution, maybe you could help me out :-) thanks

**Comment by luizbills** [comment]
These two things you pointed are default for any WordPress using SQLite. You should check in the WordPress documentation if it's possible change that with hooks.
